-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Jul 16, 2022 at 07:25 PM
-- Server version: 10.4.24-MariaDB
-- PHP Version: 8.0.19

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `be16_cr10_michalgarrigosa-biglibrary`
--

-- --------------------------------------------------------

--
-- Table structure for table `book_library`
--

CREATE TABLE `book_library` (
  `id` int(11) NOT NULL,
  `title` varchar(100) DEFAULT NULL,
  `image` varchar(100) DEFAULT NULL,
  `isbn` varchar(100) DEFAULT NULL,
  `short_description` text DEFAULT NULL,
  `type` varchar(10) DEFAULT NULL,
  `author_first_name` varchar(100) DEFAULT NULL,
  `author_last_name` varchar(100) DEFAULT NULL,
  `publisher_name` varchar(100) DEFAULT NULL,
  `publisher_address` varchar(100) DEFAULT NULL,
  `publish_date` date DEFAULT NULL,
  `status` varchar(100) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `book_library`
--

INSERT INTO `book_library` (`id`, `title`, `image`, `isbn`, `short_description`, `type`, `author_first_name`, `author_last_name`, `publisher_name`, `publisher_address`, `publish_date`, `status`) VALUES
(0, 'Die Tribute von Panem 1. Tödliche Spiele', NULL, '3789121274', 'er erste Band der Bestseller-Trilogie Die Welt, wie wir sie kennen, existiert nicht mehr. Kriege und Naturkatastrophen haben das Land zerstört. Aus den Trümmern ist Panem entstanden, geführt von einer unerbittlichen Regierung. Alljährlich finden grausame Hungerspiele statt, bei denen nur ein Einziger überleben darf. Als die sechzehnjährige Katniss erfährt, dass ihre kleine Schwester Prim als Teilnehmerin ausgelost wurde, meldet sie sich an ihrer Stelle freiwillig. Seite an Seite mit dem gleichaltrigen Peeta zieht sie in den Kampf. Wider alle Regeln rettet er ihr das Leben. Katniss beginnt zu zweifeln – kann es wirklich nur einen Sieger geben? Die atemberaubende, faszinierende Gesellschaftskritik voller Spannung – vielfach ausgezeichnet und aktueller denn je.', 'Fatasy', 'Suzanne', 'Collins', 'Verlag Friedrich Oetinger GmbH', 'Max-Brauer-Allee 34\r\n22765 Hamburg\r\nTelefon: +49 (0)40 607909-02\r\nTelefax: +49 (0)40 607909-610\r\nE-M', '0000-00-00', 'On Demand'),
(0, 'Die Tribute von Panem 2: Gefährliche Liebe', '', '', 'Der zweite Band der Bestseller-Trilogie Nachdem sie die brutalen Hungerspiele gewonnen hat, kehrt Katniss in ihr Distrikt zurück und hofft auf eine friedliche Zukunft. Doch Gerüchte, dass sich Widerstand gegen das Kapitol regt, machen die Runde. Die Spur führt zu Katniss und Peeta, in denen immer mehr Menschen ein Symbol der Rebellion sehen. Wenn Katniss und Peeta die Welt nicht davon überzeugen können, ein glückliches Liebespaar zu sein, kann das schreckliche Konsequenzen haben. Katniss muss sich entscheiden - zwischen Freiheit und Sicherheit, zwischen Leben und Tod … Die Fortsetzung des Bestsellers „Die Tribute von Panem. Tödliche Spiele.\" Der Kampf ums Überleben geht in eine neue Runde!', '', 'Suzanne', 'Collins', 'Verlag Friedrich Oetinger GmbH', 'Max-Brauer-Allee 34\r\n22765 Hamburg\r\nTelefon: +49 (0)40 607909-02\r\nTelefax: +49 (0)40 607909-610\r\nE-M', '0000-00-00', 'On Demand'),
(0, 'Die Tribute von Panem 1. Tödliche Spiele', NULL, '3789121274', 'er erste Band der Bestseller-Trilogie Die Welt, wie wir sie kennen, existiert nicht mehr. Kriege und Naturkatastrophen haben das Land zerstört. Aus den Trümmern ist Panem entstanden, geführt von einer unerbittlichen Regierung. Alljährlich finden grausame Hungerspiele statt, bei denen nur ein Einziger überleben darf. Als die sechzehnjährige Katniss erfährt, dass ihre kleine Schwester Prim als Teilnehmerin ausgelost wurde, meldet sie sich an ihrer Stelle freiwillig. Seite an Seite mit dem gleichaltrigen Peeta zieht sie in den Kampf. Wider alle Regeln rettet er ihr das Leben. Katniss beginnt zu zweifeln – kann es wirklich nur einen Sieger geben? Die atemberaubende, faszinierende Gesellschaftskritik voller Spannung – vielfach ausgezeichnet und aktueller denn je.', 'Fatasy', 'Suzanne', 'Collins', 'Verlag Friedrich Oetinger GmbH', 'Max-Brauer-Allee 34\r\n22765 Hamburg\r\nTelefon: +49 (0)40 607909-02\r\nTelefax: +49 (0)40 607909-610\r\nE-M', '0000-00-00', 'On Demand'),
(0, 'Die Tribute von Panem 2: Gefährliche Liebe', '', '', 'Der zweite Band der Bestseller-Trilogie Nachdem sie die brutalen Hungerspiele gewonnen hat, kehrt Katniss in ihr Distrikt zurück und hofft auf eine friedliche Zukunft. Doch Gerüchte, dass sich Widerstand gegen das Kapitol regt, machen die Runde. Die Spur führt zu Katniss und Peeta, in denen immer mehr Menschen ein Symbol der Rebellion sehen. Wenn Katniss und Peeta die Welt nicht davon überzeugen können, ein glückliches Liebespaar zu sein, kann das schreckliche Konsequenzen haben. Katniss muss sich entscheiden - zwischen Freiheit und Sicherheit, zwischen Leben und Tod … Die Fortsetzung des Bestsellers „Die Tribute von Panem. Tödliche Spiele.\" Der Kampf ums Überleben geht in eine neue Runde!', '', 'Suzanne', 'Collins', 'Verlag Friedrich Oetinger GmbH', 'Max-Brauer-Allee 34\r\n22765 Hamburg\r\nTelefon: +49 (0)40 607909-02\r\nTelefax: +49 (0)40 607909-610\r\nE-M', '0000-00-00', 'On Demand'),
(0, 'Auris - Der Klang des Bösen', NULL, '342630841X', 'Ein markerschütternder Schrei reißt den 15-jährigen Silvan Berg aus der Betrachtung eines Schmetterlings. Silvan rennt los, quer über das herrschaftliche Anwesen seiner Eltern am Kleinen Wannsee in Berlin – und kommt gerade noch rechtzeitig, um seine geliebte Mutter aus einem Fenster im dritten Stock der Villa stürzen zu sehen. Für den Bruchteil einer Sekunde meint er, oben seinen Vater zu erkennen.\r\n\r\nNiemand auf der Polizeistation nimmt den panischen Jugendlichen ernst, der etwas vom Mord an seiner Mutter stammelt – niemand außer Matthias Hegel. Der forensische Phonetiker kann hören, dass Silvan nicht lügt. Mit Hilfe der engagierten True-Crime-Podcasterin Jula Ansorge beginnt Hegel in einem Fall zu ermitteln, in dem nichts ist, wie es scheint … und für dessen Lösung er sehenden Auges sein Leben aufs Spiel setzt.', 'Thriller', 'Sebastian ', 'Fitzek', 'Droemer TB', 'Verlagsgruppe Droemer Knaur GmbH & Co. KG\r\nHilblestraße 54\r\n80636 München', '0000-00-00', 'On Demand'),
(0, 'Auris - Die Frequenz des Todes', NULL, '342630760X', '»Hilfe, mein Baby ist weg! Hier ist nur Blut …« Nach kurzen Kampfgeräuschen bricht der panische Notruf einer Mutter bei der Nummer 112 plötzlich ab. Wenn jemand aus diesem Tonfragment Rückschlüsse auf den Aufenthaltsort der Frau ziehen kann, dann der forensische Phonetiker Matthias Hegel – den einige nach wie vor für einen Mörder halten.\r\nTrue-Crime-Podcasterin Jula Ansorge ist es zwar gelungen, Hegel vom Mordverdacht an seiner Frau zu entlasten, doch dabei ist sie der dunklen Seite des genialen Profilers deutlich zu nahe gekommen.\r\nAls Hegel nun im Fall des entführten Babys erneut auf ihre Recherche-Fähigkeiten zurückgreifen will, weigert Jula sich zunächst. Doch kann sie das Baby und seine Mutter wirklich ihrem Schicksal überlassen? Und was ist mit den Informationen zu ihrem tot geglaubten Bruder Moritz, die Hegel ihr angeblich beschaffen will?\r\n', NULL, 'Sebastian ', 'Fitzek', 'Droemer TB', 'Verlagsgruppe Droemer Knaur GmbH & Co. KG\r\nHilblestraße 54\r\n80636 München', '0000-00-00', 'On Demand'),
(0, 'Der Bewunderer', NULL, '3944676386', 'Auf einer riesigen, kunstvoll bemalten Leinwand liegt eine Frau. Ihr Blick ist starr in den Himmel gerichtet. Sie atmet nicht mehr. Spezialermittlerin Laura Kern kann kaum die Augen von dem bizarren Fund abwenden. Jemand hat sie in ein Abendkleid und knallrote High Heels gezwängt, um sie in seinem Kunstwerk zu verewigen. Doch warum hat der Täter die Tote außerdem mit einer Rettungsweste und einem Blumenstrauß ausgestattet? Fieberhaft versucht Laura, den Mörder zu stoppen, aber der hat bereits sein nächstes Opfer auf einer Leinwand platziert. Und Laura ist ihm näher, als sie glaubt ...', 'Thriller', 'Catherine ', 'Shepherd', 'Kafel Verlag', 'Franz-Radziwill-Weg 12, 26389 Wilhelmshaven, Deutschland', '0000-00-00', 'On Demand'),
(0, 'Auris - Die Frequenz des Todes', NULL, '342630760X', '»Hilfe, mein Baby ist weg! Hier ist nur Blut …« Nach kurzen Kampfgeräuschen bricht der panische Notruf einer Mutter bei der Nummer 112 plötzlich ab. Wenn jemand aus diesem Tonfragment Rückschlüsse auf den Aufenthaltsort der Frau ziehen kann, dann der forensische Phonetiker Matthias Hegel – den einige nach wie vor für einen Mörder halten.\r\nTrue-Crime-Podcasterin Jula Ansorge ist es zwar gelungen, Hegel vom Mordverdacht an seiner Frau zu entlasten, doch dabei ist sie der dunklen Seite des genialen Profilers deutlich zu nahe gekommen.\r\nAls Hegel nun im Fall des entführten Babys erneut auf ihre Recherche-Fähigkeiten zurückgreifen will, weigert Jula sich zunächst. Doch kann sie das Baby und seine Mutter wirklich ihrem Schicksal überlassen? Und was ist mit den Informationen zu ihrem tot geglaubten Bruder Moritz, die Hegel ihr angeblich beschaffen will?\r\n', NULL, 'Sebastian ', 'Fitzek', 'Droemer TB', 'Verlagsgruppe Droemer Knaur GmbH & Co. KG\r\nHilblestraße 54\r\n80636 München', '0000-00-00', 'On Demand'),
(0, 'Der Bewunderer', NULL, '3944676386', 'Auf einer riesigen, kunstvoll bemalten Leinwand liegt eine Frau. Ihr Blick ist starr in den Himmel gerichtet. Sie atmet nicht mehr. Spezialermittlerin Laura Kern kann kaum die Augen von dem bizarren Fund abwenden. Jemand hat sie in ein Abendkleid und knallrote High Heels gezwängt, um sie in seinem Kunstwerk zu verewigen. Doch warum hat der Täter die Tote außerdem mit einer Rettungsweste und einem Blumenstrauß ausgestattet? Fieberhaft versucht Laura, den Mörder zu stoppen, aber der hat bereits sein nächstes Opfer auf einer Leinwand platziert. Und Laura ist ihm näher, als sie glaubt ...', 'Thriller', 'Catherine ', 'Shepherd', 'Kafel Verlag', 'Franz-Radziwill-Weg 12, 26389 Wilhelmshaven, Deutschland', '0000-00-00', 'On Demand'),
(0, 'Du warst ganz allein', NULL, '253012854', '»Mami, ich komme jetzt nach Hause.«\r\n\r\nJaiden Cranstons persönlicher Horrortrip beginnt an dem Tag, an dem sie ihren sechsjährigen Sohn Dave als vermisst gemeldet hat.\r\n\r\nWas er tut, ist nicht unrecht. Aber wie es im Leben so ist, wird man von der Vergangenheit immer eingeholt. Egal wie sehr man sich dagegen wehrt.\r\nEr hat sich gewehrt. Einen neuen Weg eingeschlagen, sich behauptet in der unwirklichen Welt, die täglich kälter zu werden scheint.\r\nAlles hat sich geändert, als das Unglück vor fünfzehn Jahren passiert ist. An das er so lange nicht mehr gedacht, das er verdrängt hat, weil es ja nicht seine Schuld war. Und nun hat er einen Plan. Allerdings muss er dafür jeden aus dem Weg räumen, der ihm im Weg steht.\r\nEinen nach dem anderen.', 'Thriller', 'Andrew', 'Holland', 'Kafel Verlag', 'Franz-Radziwill-Weg 12, \r\n26389 Wilhelmshaven, Deutschland', '0000-00-00', 'On Demand'),
(0, 'Eichen müssen her!: Das Dreigestirn', NULL, '3982360617', 'Kurz gesagt, um alles. Die Erde ist der endgültigen Zerstörung nahe und so tun sich Wesen aus verschiedenen Zeiten und Welten zusammen, um das drohende Schicksal im letzten Moment noch abzuwenden.\r\nDie Handlung spielt sich, beginnend in Irland im Jahr 822 und später hauptsächlich in Deutschland und Portugal ab. Dabei werden auch wahre geschichtliche Ereignisse bis in die heutige Zeit mit den Fantasy-Figuren des Buches in Zusammenhang gebracht.\r\nImmer wieder wird ein Einblick in das Leben auf dem fernen Planeten Aquarius gegeben, wo eine hoch entwickelte Spezies bereits seit Äonen von Jahrtausenden in Frieden und nachhaltig mit allen, sie umgebenden Geschöpfen und der Natur lebt. Dort entschließt sich eine kleine Gruppe von lebenslustigen Teenagern, mehr zum Spaß als im Ernst, die Erde, von der sie kürzlich erst in Planetenkunde gehört hatten, vor ihrem, offensichtlich bereits vorprogrammierten Ende zu bewahren. Durch einen Unfall, (Oder hatte dies eine geheime Macht ganz gründlich bereits im Voraus geplant?), inkarnieren sich Cerafine und ihre Mitgeschwister unabsichtlich in neuen Müttern auf der Erde.', 'Fantasy', 'Amanda', 'Gruenschild', 'Untschi-Verlag ', 'Haus Waldfriede 1\r\n65391 Lorch', '0000-00-00', 'On Demand'),
(0, 'Seele aus Eis', NULL, '1519035160', 'Schwarze Asche, die von einem brennenden Himmel regnet. Das ist nur einer der Träume, die Lena seit Monaten den Schlaf rauben. Ihr sonst so normales Leben wird zunehmend eigenartiger und gefährlicher, denn ihre Albträume fangen an, sich nach und nach zu bewahrheiten. Als sie beinahe ertrinkt, glauben ihre Freunde an einen Unfall, doch Lena weiß es besser – jemand hat versucht, sie umzubringen. Schnell verdächtigt sie den mysteriösen Darian, denn trotz seines charmanten Auftretens wird sie den Gedanken nicht los, dass sich hinter seiner freundlichen Fassade etwas Düsteres verbirgt.', 'Fantasy', 'Maria', 'Rapp', 'Amazon Fulfillment Verlag]', 'Amazon Europe Core S.à r.l. (Société à responsabilité limitée), 38 avenue John F. Kennedy, L-1855 Lu', '0000-00-00', 'On Demand'),
(0, 'Als die Tage leiser wurden', NULL, '2496708858', 'Cecilia führt zusammen mit ihrer Freundin Kat ein kleines Café in der Half Moon Street. Sie liebt London und ihre Arbeit, doch seit dem plötzlichen Verlust ihres Vaters ist ihr Leben vollkommen aus dem Takt geraten.\r\n\r\nJeden Tag besucht der bekannte Musiker Lukas Tanner das Café. Er verbringt immer mehr Zeit mit Cecilia und hilft ihr dabei, die Erinnerungen an ihren Vater und ihr Zuhause in Deutschland zum Leben zu erwecken. Doch bald stellt sich heraus, dass Lukas mehr über sie und ihre Familie weiß, als er zugibt.\r\n\r\nWie viel Wahrheit verträgt die Liebe? Wie viel Verschwiegenheit braucht sie?', 'Roman', 'Josephine', 'Cantrell', 'Tinte & Feder', 'mikewarth media\r\nMichael Höllwarth\r\nNußtobel 20\r\n73614 Schorndorf', '0000-00-00', 'On Demand'),
(0, 'Alle sieben Wellen', NULL, '222444556', 'Erstens: Sie kennen Emmi Rothner und Leo Leike? Dann haben Sie also \"Gut gegen Nordwind\" gelesen, jene ungewöhnliche Liebesgeschichte, in der sich zwei Menschen, die einander nie gesehen haben, per E-Mail rettungslos verlieben. Zweitens: Für Sie ist die Geschichte von Emmi und Leo und ihrer unerfüllten Liebe abgeschlossen. Mag sein. Aber nicht für Emmi und Leo! Drittens: Sie sind der Ansicht, dass die Liebenden zumindest eine einzige wirkliche Begegnung verdient hätten und der Roman eine zweite Chance auf ein anderes Ende? Bitte, hier haben Sie\'s! Viertens: Sie haben keine Ahnung, wovon hier die Rede ist? Kein Problem. In diesem Buch erfahren Sie alles: von Leos Rückkehr aus Boston, von Emmis Eheproblemen und von der siebenten Welle, die immer für Überraschungen gut ist.', 'Roman', 'Daniel', 'Glattauer', 'Deuticke Verlag', 'Prinz-Eugen-Str. 30\r\nA-1040 Wien', '0000-00-00', 'On Demand'),
(0, 'Die Frau auf Nordstrand', NULL, '249670111X', 'Ein sehr persönlicher Fall für die Inselkommissarin von Bestsellerautorin Anna Johannsen.\r\n\r\nKurz vor Urlaubsende wird die LKA-Kommissarin Lena Lorenzen von ihrem Kollegen Ole Kotten zu Hilfe gerufen. Auf Nordstrand, einer Halbinsel vor Husum, ist eine Leiche gefunden worden. Die Autopsie ergibt, dass es sich um die aus Thailand stammende Lawan Yao Yun handelt, die vor mehreren Monaten von ihrem deutschen Ehemann als vermisst gemeldet wurde.\r\n\r\nVon Anfang an steht der Ehemann unter Verdacht. Doch selbst als immer mehr Indizien gegen ihn sprechen, ist Lena nicht davon überzeugt, dass er der Täter ist. Ihre Suche nach weiteren Ermittlungsansätzen entwickelt sich zu einem Wettlauf mit der Zeit ...', NULL, 'Anna', 'Johannsen', 'Edition M', 'Bellinger Weg 14a\r\n68239 Mannheim', '0000-00-00', 'On Demand');

COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
